apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-node
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: staging
        image: quay.io/karthik_jk/test-node@sha256:9a714c31066f163057f543e4d52f775a1a27dbdda4d2026a9917bbab16e4e580
        name: container-image
        resources: {}
status: {}
