apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-node
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-node
    app.kubernetes.io/part-of: test-application
  name: test-node
  namespace: jephilli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-node
    spec:
      containers:
      - image: quay.io/karthik_jk/test-node@sha256:9a714c31066f163057f543e4d52f775a1a27dbdda4d2026a9917bbab16e4e580
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
